"""11.03.2025 delete username and add timestamp

Revision ID: 6cb6e1027146
Revises: 355e520af69c
Create Date: 2025-03-11 15:21:28.974303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cb6e1027146'
down_revision: Union[str, None] = '355e520af69c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('time_updated', sa.DateTime(), nullable=False))
    op.create_unique_constraint(None, 'statistics', ['id'])
    op.drop_column('statistics', 'name_user')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('statistics', sa.Column('name_user', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'statistics', type_='unique')
    op.drop_column('statistics', 'time_updated')
    # ### end Alembic commands ###
