"""edit relationship in Book and Author

Revision ID: 8941ce1a2e5f
Revises: da8ebb26ce4f
Create Date: 2025-01-28 13:24:15.323671

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8941ce1a2e5f'
down_revision: Union[str, None] = 'da8ebb26ce4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'authors', ['id'])
    op.create_unique_constraint(None, 'books', ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'books', type_='unique')
    op.drop_constraint(None, 'authors', type_='unique')
    # ### end Alembic commands ###
