"""three migration

Revision ID: f28334d513b9
Revises: 069a2f271dd2
Create Date: 2025-02-19 16:20:39.181396

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f28334d513b9'
down_revision: Union[str, None] = '069a2f271dd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('permissions_name_key', 'permissions', type_='unique')
    op.drop_constraint('roles_name_key', 'roles', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('roles_name_key', 'roles', ['name'])
    op.create_unique_constraint('permissions_name_key', 'permissions', ['name'])
    # ### end Alembic commands ###
